# Generated by Django 5.2.6 on 2025-10-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
