# Generated by Django 5.2.6 on 2025-10-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='images')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
