# Generated by Django 5.2.6 on 2025-10-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_inscription_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
