# Generated by Django 5.2.6 on 2025-10-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_inscription_email_alter_inscription_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
