# Generated by Django 5.2.6 on 2025-10-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_inscription_email_alter_inscription_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
