# Generated by Django 5.2.7 on 2025-11-04 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='joueur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.inscription'),
        ),
    ]
