# Generated by Django 5.2.7 on 2025-11-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_score_joueur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
