# Generated by Django 5.2.7 on 2025-11-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_score_joueur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='image',
        ),
    ]
